#!/usr/bin/env bash
# vps_auto_installer.sh
# Full-featured VPS Auto Installer (Ubuntu + Debian)
# Features: base tools, Nginx+PHP+MariaDB (optional), XRay (VMESS/VLESS/Trojan/WS),
# SlowDNS (basic), UDP helper (badvpn-udpgw), user management (quota/expiry), menu UI
# Author: Generated by ChatGPT for user yeminhtet4541
# NOTE: Run as root. Tested on Ubuntu 20.04/22.04 and Debian 10/11/12.

#!/usr/bin/env bash
# DOTYCAT-style VPS Dashboard Installer
# Version: 1.2.8
# OS: Ubuntu 22.04 / Debian 11
# Author: DOTYCAT TEAM
# Website: WWW.DOTYCAT.COM

set -euo pipefail
BASE_DIR="/opt/vps-dashboard"
USER_DB="/etc/vps_users.csv"
XDIR="/usr/local/bin"

log(){ echo -e "[\e[1;32mOK\e[0m] $*"; }
info(){ echo -e "[\e[1;34m..\e[0m] $*"; }
err(){ echo -e "[\e[1;31mERR\e[0m] $*" >&2; }

require_root(){ [ "$EUID" -ne 0 ] && { err "Run as root"; exit 1; } }
mkdir_if(){ [ -d "$1" ] || mkdir -p "$1"; }

init_user_db(){ [ ! -f "$USER_DB" ] && echo "username,uuid,quota_gb,expire_date,protocol,created_at" >$USER_DB && chmod 600 $USER_DB && log "User DB initialized"; }
add_user(){ read -rp "Username: " u; grep -qi "^$u," $USER_DB && { err "User exists"; return; }; uuid=$(cat /proc/sys/kernel/random/uuid); read -rp "Quota (GB, 0=unlimited): " q; read -rp "Expire date (YYYY-MM-DD or 0=never): " e; read -rp "Protocol (vless/vmess/ssh/trojan/socks): " p; created=$(date +%F); echo "$u,$uuid,$q,$e,$p,$created" >>$USER_DB; log "User $u added"; }
del_user(){ read -rp "Username to delete: " u; grep -qi "^$u," $USER_DB || { err "User not found"; return; }; sed -i "/^$u,/Id" $USER_DB; log "User $u removed"; }
list_users(){ column -t -s, $USER_DB | sed -n '2,$p'; }
cleanup_expired(){ today=$(date +%F); awk -F, 'NR==1{print;next} {if($4=="0"||$4>"'"$today"'"){print} else {print "EXPIRE,"$0 > "/tmp/expired_users.txt"}}' $USER_DB >$USER_DB.new; mv $USER_DB.new $USER_DB; [ -f /tmp/expired_users.txt ] && log "Expired users moved to /tmp/expired_users.txt"; }
user_menu(){ while true; do clear; echo "---- User Management ----"; echo "1) Add user"; echo "2) Delete user"; echo "3) List users"; echo "4) Cleanup expired users"; echo "0) Back"; read -rp "Choose: " u; case $u in 1) add_user;;2) del_user;;3) list_users; read -rp "Press Enter...";;4) cleanup_expired;;0) return;;*) echo "Invalid"; sleep 1;; esac; done; }
install_base(){ info "Installing base packages..."; apt-get update -y; apt-get upgrade -y; apt-get install -y curl wget git unzip lsb-release net-tools htop screen bash-completion ufw python3 python3-pip; log "Base packages installed"; }
install_nginx(){ info "Installing NGINX..."; apt-get install -y nginx; systemctl enable --now nginx; log "NGINX installed"; }
install_xray(){ info "Installing XRay..."; mkdir_if "$BASE_DIR"; XR_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-$(uname -m).zip"; tmp="/tmp/xray.zip"; curl -L -o "$tmp" "$XR_URL"; unzip -o "$tmp" -d /tmp/xray >/dev/null; install -m 755 /tmp/xray/xray "$XDIR/xray"; mkdir_if /etc/xray; cat >/etc/systemd/system/xray.service <<'EOF'
[Unit]
Description=XRay Service
After=network.target
[Service]
Type=simple
ExecStart=/usr/local/bin/xray run -config /etc/xray/config.json
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF
 systemctl daemon-reload; systemctl enable --now xray || true; log "XRay installed"; }
write_sample_xray_config(){ info "Writing sample XRay JSON config"; mkdir_if /etc/xray; cat >/etc/xray/config.json <<'EOF'
{
  "inbounds":[{"port":80,"listen":"127.0.0.1","protocol":"vless","settings":{"clients":[{"id":"00000000-0000-0000-0000-000000000000","flow":""}]},"streamSettings":{"network":"ws","wsSettings":{"path":"/vless"}}}],
  "outbounds":[{"protocol":"freedom","settings":{}}]
}
EOF
 log "Sample XRay config written"; }
install_slowdns(){ info "Installing SlowDNS..."; SD_URL="https://github.com/AdguardTeam/SlowDNS/releases/latest/download/slowdns-linux-$(uname -m)"; mkdir_if /opt/slowdns; curl -L -o /opt/slowdns/slowdns "$SD_URL"; chmod +x /opt/slowdns/slowdns; log "SlowDNS installed"; }
main_menu(){ while true; do clear; echo "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"; echo "┃   VPS Dashboard - DOTYCAT Style                     ┃"; echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"; echo; echo "[01] SSH/WS MENU"; echo "[02] VMESS MENU"; echo "[03] VLESS MENU"; echo "[04] TROJAN MENU"; echo "[05] SOCKS MENU"; echo "[06] User management"; echo "[07] SlowDNS → install automatically"; echo; echo "Tools:"; echo "[08] DNS PANEL"; echo "[09] DOMAIN PANEL"; echo "[10] NETGUARD PANEL"; echo "[11] VPN PORT INFO"; echo "[12] CLEAN VPS LOGS"; echo "[13] VPS STATUS"; echo; echo "[00] EXIT"; read -rp "Choose: " c; case $c in 1) echo "SSH/WS MENU selected"; sleep 2;;2) echo "VMESS MENU selected"; sleep 2;;3) echo "VLESS MENU selected"; sleep 2;;4) echo "TROJAN MENU selected"; sleep 2;;5) echo "SOCKS MENU selected"; sleep 2;;6) user_menu;;7) install_slowdns;;8) echo "DNS PANEL"; sleep 2;;9) echo "DOMAIN PANEL"; sleep 2;;10) echo "NETGUARD PANEL"; sleep 2;;11) echo "VPN PORT INFO"; sleep 2;;12) echo "CLEAN VPS LOGS"; sleep 2;;13) echo "VPS STATUS"; sleep 2;;0) exit 0;;*) echo "Invalid"; sleep 1;; esac; done; }
require_root; mkdir_if $BASE_DIR; init_user_db; install_base; install_nginx; install_xray; write_sample_xray_config; main_menu



set -euo pipefail
LANG=C
BASE_DIR="/opt/vps-installer"
USER_DB="/etc/vps_users.csv"
XDIR="/usr/local/bin"

#!/usr/bin/env bash
# vps_auto_installer.sh
# Linux-ready VPS Auto Installer (Ubuntu + Debian)
# Features: base tools, Nginx+PHP+MariaDB (optional), XRay, SlowDNS, UDP helper, user management, interactive menu
# Line endings converted to LF for Linux

set -euo pipefail
LANG=C
BASE_DIR="/opt/vps-installer"
USER_DB="/etc/vps_users.csv"
XDIR="/usr/local/bin"

log(){ echo -e "[\e[1;32mOK\e[0m] $*"; }
err(){ echo -e "[\e[1;31mERR\e[0m] $*" >&2; }
info(){ echo -e "[\e[1;34m..\e[0m] $*"; }

require_root(){ if [ "$EUID" -ne 0 ]; then err "This script must be run as root."; exit 1; fi }
mkdir_if(){ [ -d "$1" ] || mkdir -p "$1"; }

detect_os(){
  if [ -f /etc/os-release ]; then . /etc/os-release; OS_NAME="$ID"; OS_VER="$VERSION_ID"; else err "Unsupported OS"; exit 1; fi
  info "Detected OS: $OS_NAME $OS_VER"
  case "$OS_NAME" in ubuntu|debian) ;; *) err "Supports Ubuntu/Debian only"; exit 1;; esac
}

apt_update(){ export DEBIAN_FRONTEND=noninteractive; apt-get update -y; apt-get upgrade -y; }
install_base(){ info "Installing base packages..."; apt-get install -y curl wget git ca-certificates lsb-release apt-transport-https jq unzip net-tools screen htop bash-completion ufw fail2ban python3 python3-pip; log "Base packages installed"; }
install_web_stack(){ read -rp "Install web stack (Nginx + PHP + MariaDB)? [y/N]: " yn; yn=${yn:-N}; if [[ "$yn" =~ ^[Yy]$ ]]; then info "Installing Nginx..."; apt-get install -y nginx; systemctl enable --now nginx; info "Installing PHP..."; apt-get install -y php-fpm php-cli php-mysql php-curl php-xml php-mbstring; systemctl enable --now php*-fpm || true; info "Installing MariaDB..."; apt-get install -y mariadb-server; systemctl enable --now mariadb; log "Web stack installed"; else info "Skipping web stack"; fi }
install_xray(){ info "Installing XRay core..."; mkdir_if "$BASE_DIR"; XR_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-$(uname -m).zip"; tmp="/tmp/xray.zip"; curl -L -o "$tmp" "$XR_URL"; unzip -o "$tmp" -d /tmp/xray >/dev/null; install -m 755 /tmp/xray/xray "$XDIR/xray"; mkdir_if /etc/xray; cat >/etc/systemd/system/xray.service <<'EOF'
[Unit]
Description=XRay Service
After=network.target
[Service]
Type=simple
ExecStart=/usr/local/bin/xray run -config /etc/xray/config.json
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF
 systemctl daemon-reload; systemctl enable --now xray || true; log "XRay installed. Default config at /etc/xray/config.json"; }
write_sample_xray_config(){ info "Writing sample XRay JSON config"; mkdir_if /etc/xray; cat >/etc/xray/config.json <<'EOF'
{
  "inbounds":[{"port":80,"listen":"127.0.0.1","protocol":"vless","settings":{"clients":[{"id":"00000000-0000-0000-0000-000000000000","flow":""}]},"streamSettings":{"network":"ws","wsSettings":{"path":"/vless"}}}],
  "outbounds":[{"protocol":"freedom","settings":{}}]
}
EOF
 log "Sample XRay config written"; }
install_slowdns(){ info "Installing SlowDNS helper..."; SD_URL="https://github.com/AdguardTeam/SlowDNS/releases/latest/download/slowdns-linux-$(uname -m)"; mkdir_if /opt/slowdns; curl -L -o /opt/slowdns/slowdns "$SD_URL" || err "Manual install needed"; chmod +x /opt/slowdns/slowdns; log "SlowDNS installed"; }
install_udp_helper(){ info "Installing badvpn-udpgw..."; apt-get install -y cmake build-essential libssl-dev || true; mkdir_if /opt/badvpn; cd /tmp; [ ! -f badvpn-1.999.130.tar.gz ] && wget -q https://github.com/ambrop72/badvpn/archive/refs/tags/1.999.130.tar.gz; tar xzf badvpn-1.999.130.tar.gz; cd badvpn-1.999.130; cmake -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 . && make -j2 || true; install -m 755 badvpn-udpgw /usr/local/bin/badvpn-udpgw; cat >/etc/systemd/system/badvpn-udpgw.service <<'EOF'
[Unit]
Description=badvpn udpgw
After=network.target
[Service]
ExecStart=/usr/local/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1024
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF
 systemctl daemon-reload; systemctl enable --now badvpn-udpgw || true; log "badvpn-udpgw installed and running"; }
init_user_db(){ [ ! -f "$USER_DB" ] && echo "username,uuid,quota_gb,expire_date,protocol,created_at" >$USER_DB && chmod 600 $USER_DB && log "User DB initialized"; }
add_user(){ read -rp "Username: " u; grep -qi "^$u," $USER_DB && { err "User exists"; return; }; uuid=$(cat /proc/sys/kernel/random/uuid); read -rp "Quota (GB, 0=unlimited): " q; read -rp "Expire date (YYYY-MM-DD or 0=never): " e; read -rp "Protocol (vless/vmess/ssh/trojan/socks): " p; created=$(date +%F); echo "$u,$uuid,$q,$e,$p,$created" >>$USER_DB; log "User $u added"; }
del_user(){ read -rp "Username to delete: " u; grep -qi "^$u," $USER_DB || { err "User not found"; return; }; sed -i "/^$u,/Id" $USER_DB; log "User $u removed"; }
list_users(){ column -t -s, $USER_DB | sed -n '2,$p'; }
cleanup_expired(){ today=$(date +%F); awk -F, 'NR==1{print;next} {if($4=="0"||$4>"'"$today"'"){print} else {print "EXPIRE,"$0 > "/tmp/expired_users.txt"}}' $USER_DB >$USER_DB.new; mv $USER_DB.new $USER_DB; [ -f /tmp/expired_users.txt ] && log "Expired users moved to /tmp/expired_users.txt"; }
user_menu(){ while true; do clear; echo "---- User Management ----"; echo "1) Add user"; echo "2) Delete user"; echo "3) List users"; echo "4) Cleanup expired users"; echo "0) Back"; read -rp "Choose: " u; case $u in 1) add_user;;2) del_user;;3) list_users; read -rp "Press Enter...";;4) cleanup_expired;;0) return;;*) echo "Invalid"; sleep 1;; esac; done; }
main_menu(){ while true; do clear; echo "=============================================="; echo "  VPS Auto Installer — Ubuntu / Debian"; echo "=============================================="; echo "1) Update & install base packages"; echo "2) Install web stack (Nginx/PHP/MariaDB)"; echo "3) Install XRay core"; echo "4) Write sample XRay config"; echo "5) Install SlowDNS helper"; echo "6) Install UDP helper (badvpn-udpgw)"; echo "7) User management"; echo "8) Show services status"; echo "9) Initialize user DB"; echo "0) Exit"; read -rp "Choose: " c; case $c in 1) apt_update; install_base;;2) install_web_stack;;3) install_xray;;4) write_sample_xray_config;;5) install_slowdns;;6) install_udp_helper;;7) user_menu;;8) systemctl status nginx xray badvpn-udpgw mariadb --no-pager || true;;9) init_user_db;;0) exit 0;;*) echo "Invalid"; sleep 1;; esac; echo; read -rp "Press Enter to continue..." dummy; done; }
require_root; detect_os; mkdir_if $BASE_DIR; init_user_db; main_menu



# ---------- Helpers ----------
log(){ echo -e "[\e[1;32mOK\e[0m] $*"; }
err(){ echo -e "[\e[1;31mERR\e[0m] $*" >&2; }
info(){ echo -e "[\e[1;34m..\e[0m] $*"; }

require_root(){
  if [ "$EUID" -ne 0 ]; then
    err "This script must be run as root. Use sudo."; exit 1;
  fi
}

mkdir_if(){ [ -d "$1" ] || mkdir -p "$1"; }

detect_os(){
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_NAME="$ID"
    OS_VER="$VERSION_ID"
  else
    err "Unsupported OS"; exit 1;
  fi
  info "Detected OS: $OS_NAME $OS_VER"
  case "$OS_NAME" in
    ubuntu|debian) ;;
    *) err "This installer supports Ubuntu/Debian only."; exit 1;;
  esac
}

apt_update(){
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get upgrade -y
}

install_base(){
  info "Installing base packages..."
  apt-get install -y curl wget git ca-certificates lsb-release apt-transport-https \
    jq unzip net-tools screen htop bash-completion ufw fail2ban python3 python3-pip
  log "Base packages installed"
}

# ---------- Nginx / PHP / MariaDB ----------
install_web_stack(){
  read -rp "Install web stack (Nginx + PHP + MariaDB)? [y/N]: " yn
  yn=${yn:-N}
  if [[ "$yn" =~ ^[Yy]$ ]]; then
    info "Installing Nginx..."
    apt-get install -y nginx
    systemctl enable --now nginx
    info "Installing PHP (fpm) and extensions..."
    apt-get install -y php-fpm php-cli php-mysql php-curl php-xml php-mbstring
    systemctl enable --now php*-fpm || true
    info "Installing MariaDB..."
    apt-get install -y mariadb-server
    systemctl enable --now mariadb
    log "Web stack installed"
  else
    info "Skipping web stack"
  fi
}

# ---------- XRay install ----------
install_xray(){
  info "Installing XRay core (latest)..."
  mkdir_if "$BASE_DIR"
  XR_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-$(uname -m).zip"
  tmp="/tmp/xray.zip"
  curl -L -o "$tmp" "$XR_URL"
  unzip -o "$tmp" -d /tmp/xray >/dev/null
  install -m 755 /tmp/xray/xray "$XDIR/xray"
  mkdir_if /etc/xray
  cat >/etc/systemd/system/xray.service <<'EOF'
[Unit]
Description=XRay Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/xray run -config /etc/xray/config.json
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now xray || true
  log "XRay installed. Default config at /etc/xray/config.json (you should edit it)"
}

write_sample_xray_config(){
  info "Writing minimal sample XRay JSON config for VLESS+WS (no TLS)"
  mkdir_if /etc/xray
  cat >/etc/xray/config.json <<'EOF'
{
  "inbounds": [
    {
      "port": 80,
      "listen": "127.0.0.1",
      "protocol": "vless",
      "settings": {"clients": [{"id":"00000000-0000-0000-0000-000000000000","flow":""}]},
      "streamSettings": {"network":"ws","wsSettings":{"path":"/vless"}}
    }
  ],
  "outbounds": [{"protocol":"freedom","settings":{}}]
}
EOF
  log "Sample XRay config written (replace UUID and add TLS)"
}

# ---------- SlowDNS (basic) ----------
install_slowdns(){
  info "Installing SlowDNS client/server helper (basic)")
  # We'll download 'slowdns' binary implementations if available; otherwise provide instructions.
  # Many community implementations exist; this step will pull a popular compiled binary if present.
  SD_URL="https://github.com/AdguardTeam/SlowDNS/releases/latest/download/slowdns-linux-$(uname -m)"
  if curl -sI "$SD_URL" | head -n1 | grep -q "200"; then
    mkdir_if /opt/slowdns
    curl -L -o /opt/slowdns/slowdns "$SD_URL"
    chmod +x /opt/slowdns/slowdns
    log "SlowDNS binary installed to /opt/slowdns/slowdns"
  else
    err "Automatic SlowDNS binary not found. You can install your preferred SlowDNS binary manually in /opt/slowdns. See README.";
  fi
}

# ---------- UDP helper: badvpn-udpgw ----------
install_udp_helper(){
  info "Installing badvpn-udpgw (UDP forwarder)"
  apt-get install -y cmake build-essential libssl-dev || true
  BADVPN_DIR="/opt/badvpn"
  mkdir_if "$BADVPN_DIR"
  cd /tmp
  if [ ! -f badvpn-1.999.130.tar.gz ]; then
    wget -q https://github.com/ambrop72/badvpn/archive/refs/tags/1.999.130.tar.gz -O badvpn-1.999.130.tar.gz || true
  fi
  tar xzf badvpn-1.999.130.tar.gz || true
  cd badvpn-1.999.130
  cmake -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 . && make -j2 || true
  install -m 755 badvpn-udpgw /usr/local/bin/badvpn-udpgw || true
  cat >/etc/systemd/system/badvpn-udpgw.service <<'EOF'
[Unit]
Description=badvpn udpgw
After=network.target

[Service]
ExecStart=/usr/local/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1024
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now badvpn-udpgw || true
  log "badvpn-udpgw installed and started on 127.0.0.1:7300"
}

# ---------- User Management (CSV) ----------
init_user_db(){
  if [ ! -f "$USER_DB" ]; then
    echo "username,uuid,quota_gb,expire_date,protocol,created_at" >/etc/vps_users.csv
    chmod 600 /etc/vps_users.csv
    log "User DB initialized at $USER_DB"
  fi
}

add_user(){
  read -rp "Username: " username
  if grep -qi "^$username," "$USER_DB"; then err "User exists"; return; fi
  uuid=$(cat /proc/sys/kernel/random/uuid)
  read -rp "Quota (GB, 0 = unlimited): " quota
  read -rp "Expire date (YYYY-MM-DD or 0 = never): " expire
  read -rp "Protocol (vless/vmess/ssh/trojan/socks): " proto
  created=$(date -u +%Y-%m-%d)
  echo "$username,$uuid,$quota,$expire,$proto,$created" >> "$USER_DB"
  log "User $username added (UUID: $uuid)"
}

del_user(){
  read -rp "Username to delete: " u
  if ! grep -qi "^$u," "$USER_DB"; then err "User not found"; return; fi
  sed -i "/^$u,/Id" "$USER_DB"
  log "User $u removed"
}

list_users(){
  column -t -s, "$USER_DB" | sed -n '2,$p' || true
}

cleanup_expired(){
  today=$(date +%F)
  awk -F, 'NR==1{print $0;next} {if($4=="0" || $4=="" ) {print $0} else if ($4>"'"$today"'") {print $0} else {print "EXPIRE,"$0 > "/tmp/expired_users.txt"}}' "$USER_DB" > "$USER_DB".new || true
  mv "$USER_DB".new "$USER_DB" || true
  if [ -f /tmp/expired_users.txt ]; then
    log "Expired user entries moved to /tmp/expired_users.txt"
  fi
}

# ---------- Menu UI ----------
main_menu(){
  while true; do
    clear
    echo "=============================================="
    echo "  VPS Auto Installer — Ubuntu / Debian"
    echo "=============================================="
    echo "1) Update & install base packages"
    echo "2) Install web stack (Nginx/PHP/MariaDB)"
    echo "3) Install XRay core"
    echo "4) Write sample XRay config"
    echo "5) Install SlowDNS helper"
    echo "6) Install UDP helper (badvpn-udpgw)"
    echo "7) User management"
    echo "8) Show services status"
    echo "9) Initialize user DB"
    echo "0) Exit"
    read -rp "Choose: " c
    case "$c" in
      1) apt_update; install_base;;
      2) install_web_stack;;
      3) install_xray;;
      4) write_sample_xray_config;;
      5) install_slowdns;;
      6) install_udp_helper;;
      7) user_menu;;
      8) systemctl status nginx xray badvpn-udpgw mariadb --no-pager || true;;
      9) init_user_db;;
      0) exit 0;;
      *) echo "Invalid"; sleep 1;;
    esac
    echo; read -rp "Press Enter to continue..." dummy
  done
}

user_menu(){
  while true; do
    clear
    echo "---- User Management ----"
    echo "1) Add user"
    echo "2) Delete user"
    echo "3) List users"
    echo "4) Cleanup expired users"
    echo "0) Back"
    read -rp "Choose: " u
    case "$u" in
      1) add_user;;
      2) del_user;;
      3) list_users; read -rp "Press Enter...";;
      4) cleanup_expired;;
      0) return;;
      *) echo "Invalid"; sleep 1;;
    esac
  done
}

# ---------- Install summary / README generator ----------
write_readme(){
  cat >$BASE_DIR/README.txt <<EOF
VPS Auto Installer
==================
Files:
 - /etc/xray/config.json : XRay config
 - /etc/vps_users.csv : User DB

How to run:
 sudo bash $(basename "$0")

Notes:
 - Edit /etc/xray/config.json to set UUIDs, TLS (recommended) and domain.
 - SlowDNS binary not guaranteed; you may need to provide your own.
 - For Let's Encrypt TLS, configure Nginx as reverse proxy and obtain certs.
EOF
}

# ---------- Entrypoint ----------
require_root
detect_os
mkdir_if "$BASE_DIR"
write_readme
init_user_db

if [[ "${1:-}" == "--auto" ]]; then
  apt_update
  install_base
  install_xray
  write_sample_xray_config
  install_udp_helper
  log "Auto mode finished"
  exit 0
fi

main_menu
